# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs the clean gradle"
  lane :unit do
    gradle(task: "clean test")
  end

  desc "Runs the unit tests"
  lane :unit do
    gradle(task: "clean test")
  end

  desc "Runs the lint tests"
  lane :lint do
    gradle(task: "clean lint")
  end

  desc "Runs the functional tests"
  lane :functional do
    gradle(task: "clean connectedAndroidTest")
  end

  desc "Builds a new staging release"
  lane :build_staging do
    gradle(task: "clean assembleStaging")
  end

  desc "Builds a new prod release"
  lane :build_prod do
    gradle(task: "clean assembleProduction")
  end

  desc "Delivers a new staging release"
  lane :deliver_staging do
    hockey(
      api_token: "9c253a98022a4dd899c3ccbe589b5dea",
      apk: "./app/build/outputs/apk/staging/debug/app-staging-debug.apk",
      notes: "New version of staging"
    )
  end

  desc "Delivers a new prod release"
  lane :deliver_prod do
    hockey(
      api_token: "c7ef8b8bdfed4dfabe16cca75573d392",
      apk: "./app/build/outputs/apk/production/debug/app-production-debug.apk",
      notes: "New version of prod"
    )
  end
end
